export const INTRO_DATA = [
  {
    id: 0,
    icon: "icon",
    stepCount: "step One",
    title: "title",
    content:
      "some dummy content to explain the steps to follow. form a to so so and so.",
  },
  {
    id: 1,
    icon: "icon",
    stepCount: "step Two",
    title: "title",
    content:
      "some dummy content to explain the steps to follow. form a to so so and so.",
  },
  {
    id: 2,
    icon: "icon",
    stepCount: "step Three",
    title: "title",
    content:
      "some dummy content to explain the steps to follow. form a to so so and so.",
  },
];

export const PRODUCTS_DATA = [
  {
    id: 0,
    category: "Fruits",
    heading: "Freshly harvested Peach",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 1500,
    imgSrc: "/fruits/peach.jpg",
  },
  {
    id: 1,
    category: "Vegetable",
    heading: "Onions",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 2700,
    imgSrc: "/vegetables/onions.jpg",
  },
  {
    id: 2,
    category: "Animals",
    heading: "Healthy Cattle",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 280000,
    imgSrc: "/animals/cattle.jpg",
  },
  {
    id: 3,
    category: "Poultry",
    heading: "Large Turkey",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Units",
    price: 12000,
    imgSrc: "/poultry/turkey.jpg",
  },
  {
    id: 4,
    category: "Poultry",
    heading: "Large Chicken",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Units",
    price: 3000,
    imgSrc: "/poultry/chicken.jpg",
  },
  {
    id: 5,
    category: "Diary Milk",
    heading: "Unsaturated Milk",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Gallons",
    price: 6000,
    imgSrc: "/diary/milk.jpg",
  },
];
