export const INTRO_DATA = [
  {
    id: 0,
    // icon: "icon",
    stepCount: "step One",
    title: "Navigate",
    content:
      "Navigate through the homepage and see if there is a product you need.",
  },
  {
    id: 1,
    // icon: "icon",
    stepCount: "step Two",
    title: "Select",
    content: "Select any product you see and want to buy.",
  },
  {
    id: 2,
    // icon: "icon",
    stepCount: "step Three",
    title: "Contact",
    content: "Contact us via the phone number and e-mail address provided.",
  },
];

export const PRODUCTS_DATA = [
  {
    id: 0,
    category: "Fruits",
    heading: "Freshly harvested Peach",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 1500,
    imgSrc: "/fruits/peach.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
  {
    id: 1,
    category: "Vegetable",
    heading: "Onions",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 2700,
    imgSrc: "/vegetables/onions.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
  {
    id: 2,
    category: "Animals",
    heading: "Healthy Cattle",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "bags",
    price: 280000,
    imgSrc: "/animals/cattle.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
  {
    id: 3,
    category: "Poultry",
    heading: "Large Turkey",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Units",
    price: 12000,
    imgSrc: "/poultry/turkey.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
  {
    id: 4,
    category: "Poultry",
    heading: "Large Chicken",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Units",
    price: 3000,
    imgSrc: "/poultry/chicken.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
  {
    id: 5,
    category: "Diary Milk",
    heading: "Unsaturated Milk",
    user: "Username",
    location: "location",
    time: "time uplaoded",
    units: "Gallons",
    price: 6000,
    imgSrc: "/diary/milk.jpg",
    phoneNo: +2348012345678,
    email: "productSeller@mail.com",
  },
];
